version: 2
jobs:
 build:
   machine: true

   steps:
     - checkout

     - run:
         name: Execution of make command  
         command: make

  commit-workflow:
    jobs:
      - build:
          filters:
            tags:
              only:
                - /.*/
